name: DiaMail
version: 2.4-R1
api-version: 1.13
description: An E-Mail inside minecraft
main: team.creativecode.diamail.Main
author: TiveCS
commands:
   diamail:
      aliases: [ mail, dm, dmail]
      description: DiaMail main command
      permission: diamail.command